# Generated by Django 4.1 on 2022-12-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
